# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [1]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [2]:
# Create a 1-dimensional NumPy array using np.array()
a1 = np.array([1,4,2])

# Create a 2-dimensional NumPy array using np.array()
a2 = np.array([[4,2,1],
               [2,6,2]])

# Create a 3-dimensional Numpy array using np.array()
a3 = np.array([
    [[4,5,1],
    [7,8,2],
    [8,5,3]],

    [[5,5,1],
    [6,2,9],
    [7,4,3]]

])

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [3]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
a1.shape,a1.ndim,a1.size,type(a1)


((3,), 1, 3, numpy.ndarray)

In [4]:
# Attributes of 2-dimensional array
a2.shape,a2.ndim,a2.size,type(a2)

((2, 3), 2, 6, numpy.ndarray)

In [5]:
# Attributes of 3-dimensional array
a3.shape,a3.ndim,a3.size,type(a3)

((2, 3, 3), 3, 18, numpy.ndarray)

In [6]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd

df1 = pd.DataFrame(a1)
df1

0
0  1
1  4
2  2

In [7]:
df2 = pd.DataFrame(a2)
df2

0  1  2
0  4  2  1
1  2  6  2

In [8]:
df3 = pd.DataFrame(a3.reshape(6,3), columns=['A','B','C'])
df3

A  B  C
0  4  5  1
1  7  8  2
2  8  5  3
3  5  5  1
4  6  2  9
5  7  4  3

In [9]:
# Create an array of shape (10, 2) with only ones
ones = np.ones((10,2))
ones

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [10]:
# Create an array of shape (7, 2, 3) of only zeros
zeros = np.zeros((7,2,3))
zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [11]:
# Create an array within a range of 0 and 100 with step 3
a_100 = np.arange(0,100,3)
a_100

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [12]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
a4 = np.random.randint(10, size=(7,2))
a4

array([[6, 5],
       [7, 0],
       [1, 2],
       [7, 2],
       [8, 9],
       [6, 0],
       [9, 2]])

In [13]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
a5 = np.random.random(size=(3,5))
a5

array([[0.04563069, 0.49803582, 0.70718202, 0.7696426 , 0.65671356],
       [0.45042234, 0.2975577 , 0.46590078, 0.60494352, 0.2299852 ],
       [0.15847187, 0.40294766, 0.54142239, 0.73666669, 0.91758021]])

In [14]:
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
a6 = np.random.randint(10,size=(4,6))
a6

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [15]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
a7 = np.random.randint(1,10 , size=(3,7))

# Find the unique numbers in the array you just created
np.unique(a7)

array([1, 2, 3, 4, 5, 7, 9])

In [16]:
# Find the 0'th index of the latest array you created
a7[0]

array([9, 1, 3, 7, 4, 9, 3])

In [17]:
# Get the first 2 rows of latest array you created
a7[:2]

array([[9, 1, 3, 7, 4, 9, 3],
       [5, 3, 7, 5, 9, 7, 2]])

In [18]:
a7

array([[9, 1, 3, 7, 4, 9, 3],
       [5, 3, 7, 5, 9, 7, 2],
       [4, 9, 2, 9, 5, 2, 4]])

In [19]:
# Get the first 2 values of the first 2 rows of the latest array
a7[:2, :2]

array([[9, 1],
       [5, 3]])

In [20]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
a8 = np.random.randint(10, size=(3,5))
a9 = np.ones((3,5))

In [21]:
# Add the two arrays together
a8 + a9

array([[ 7.,  8.,  3.,  1.,  4.],
       [ 2.,  8.,  4.,  2.,  6.],
       [ 6., 10.,  4.,  6.,  2.]])

In [22]:
# Create another array of ones of shape (5, 3)
a10 = np.ones((5,3))

In [23]:
# Try add the array of ones and the other most recent array together
# a10 + a8

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

In [24]:
# Create another array of ones of shape (3, 5)
a11 = np.ones((3,5))
a11

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [26]:
# Subtract the new array of ones from the other most recent array
a11 - a9

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [27]:
# Multiply the ones array with the latest array
a11 * a9

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [28]:
# Take the latest array to the power of 2 using '**'
a11 ** 2

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [29]:
# Do the same thing with np.square()
np.square(a11)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [30]:
# Find the mean of the latest array using np.mean()
np.mean(a8)

3.8666666666666667

In [31]:
# Find the maximum of the latest array using np.max()
np.max(a8)

9

In [32]:
# Find the minimum of the latest array using np.min()
np.min(a8)

0

In [33]:
# Find the standard deviation of the latest array
np.std(a8)

2.578543947441829

In [34]:
# Find the variance of the latest array
np.var(a8)

6.648888888888889

In [35]:
# Reshape the latest array to (3, 5, 1)
a8.reshape(3,5,1)

array([[[6],
        [7],
        [2],
        [0],
        [3]],

       [[1],
        [7],
        [3],
        [1],
        [5]],

       [[5],
        [9],
        [3],
        [5],
        [1]]])

In [36]:
# Transpose the latest array
a8.T

array([[6, 1, 5],
       [7, 7, 9],
       [2, 3, 3],
       [0, 1, 5],
       [3, 5, 1]])

What does the transpose do?

It flips the # of rows and columns. E.g if the array is of shape (3,5), transpose flips it to an array of of (5,3)

In [37]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
a12 = np.random.randint(10, size=(3,3))
a13 = np.random.randint(10, size=(3,2))

In [38]:
# Perform a dot product on the two newest arrays you created
a12.dot(a13)

array([[ 88, 117],
       [100, 123],
       [ 89, 127]])

In [42]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
a14 = np.random.randint(10, size=(4,3))
a15 = np.random.randint(10, size=(4,3))

In [43]:
# Perform a dot product on the two newest arrays you created
# a14.dot(15)

It doesn't work. How would you fix it?

By transposing one of the arrays to an array of shape (3,4)

In [44]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both
a14.dot(a15.T)

array([[ 24, 102,  96,   8],
       [ 16, 114, 106,  63],
       [ 22, 123, 114,  56],
       [  8,  60,  58,   7]])

Notice how performing a transpose allows the dot product to happen.

Why is this?

Because the number of columns in the first array must match the number of rows in the second array

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [45]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
a16 = np.random.randint(10, size=(3,2))
a17 = np.random.randint(10, size=(3,2))

In [47]:
a16

array([[6, 6],
       [7, 4],
       [2, 7]])

In [48]:
a17

array([[5, 2],
       [0, 2],
       [4, 2]])

In [46]:
# Compare the two arrays with '>'
a16 > a17

array([[ True,  True],
       [ True,  True],
       [False,  True]])

What happens when you compare the arrays with `>`?

In [49]:
# Compare the two arrays with '>='
a16 >= a17

array([[ True,  True],
       [ True,  True],
       [False,  True]])

In [58]:
a16

array([[6, 6],
       [7, 4],
       [2, 7]])

In [59]:
# Find which elements of the first array are greater than 7
a16 >7

array([[False, False],
       [False, False],
       [False, False]])

In [60]:
# Which parts of each array are equal? (try using '==')
a16==a17

array([[False, False],
       [False, False],
       [False, False]])

In [62]:
# Sort one of the arrays you just created in ascending order
np.sort(a16)

array([[6, 6],
       [4, 7],
       [2, 7]])

In [63]:
# Sort the indexes of one of the arrays you just created
np.argsort(a16)

array([[0, 1],
       [0, 1],
       [0, 1]])

In [64]:
# Find the index with the maximum value in one of the arrays you've created
np.argmax(a16)

3

In [65]:
# Find the index with the minimum value in one of the arrays you've created
np.argmin(a16)

4

In [66]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
np.argmax(a16, axis=1)

array([0, 1, 1])

In [67]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
np.argmin(a16, axis=0)

array([2, 0])

In [68]:
# Create an array of normally distributed random numbers
np.random.randn(3, 5)

array([[ 0.36139561,  1.53803657, -0.03582604,  1.56464366, -2.6197451 ],
       [ 0.8219025 ,  0.08704707, -0.29900735,  0.09176078, -1.98756891],
       [-0.21967189,  0.35711257,  1.47789404, -0.51827022, -0.8084936 ]])

In [69]:
# Create an array with 10 evenly spaced numbers between 1 and 100
np.linspace(1,100,10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.